name: zam_todo
description: Todo App.
version: 0.0.1
repository: https://github.com/amsakanna/zam_todo
publish_to: "none"

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.4
  kiwi: ^3.0.0
  path_provider: ^2.0.6
  zam_block_architecture: ^0.2.0
  zam_core: ^0.6.0
  zam_event_bus: ^0.8.0
  zam_event_bus_provider: ^0.4.0
  zam_rules: ^0.2.0
  zam_view_models: ^0.1.0
  zam_command_pattern: ^0.2.0

dev_dependencies:
  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^1.0.4
  mockito: ^5.0.16
  zam_test: ^0.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/error.png
    - assets/empty-list.png

flutter_icons:
  image_path: assets/app_icon.png
  android: true
  ios: true
